spring:
  application:
    name: spring-boot-ldap-integration
  ldap:
    urls: ldap://localhost:10389
    base: ou=system
    username: uid=admin,ou=system
    password: secret
  security:
    ldap:
      authentication-strategy: simple
